# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_pattern_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='Gcode',
            field=models.FileField(default=' ', upload_to=b''),
            preserve_default=False,
        ),
    ]
